### ISSUE TITLE
Replace Phenotypic Abnormality with disease name Annotation Card

### ISSUE THREAD

**Issue by LCCarmody** [TheJacksonLaboratory/POET#101]
added new term OMIM:613989 and it didn't show in the list. FWIW, it was a treatment for disease. had to refresh in the browser to see the annotation.

**Comment by pnrobinson** [comment]
@LCCarmody  -- we will still need to add the annotation to HPOAs -- please also add annotations here
https://github.com/monarch-initiative/hpo-annotation-data

**Comment by LCCarmody** [comment]
I need to add 'phenotypic abnormality' to the annotation?  Given all the diseases could have a treatment that treats the disease, shouldn't we just have that automatically added to all diseases in HPOA? I'm happy to write a ticket, but maybe there is another way.

**Comment by pnrobinson** [comment]
upps, sorry my misunderstanding!

**Comment by iimpulse** [comment]
Acceptance Criteria:

Create an annotation to the disease using the disease checkbox. After submission, the list should display the treatment for the disease name not phenotypic abnormality

**Comment by iimpulse** [comment]
#124
