### ISSUE TITLE
Treatments won't appear after navigating to phenotypes beyond 1-10

### ISSUE THREAD

**Issue by peupeubangbang** [TheJacksonLaboratory/POET#102]
_**LIVE DEMO OF BUG**_
https://www.loom.com/share/d6c579919b1e49b09e988ef5c4b2a656

Treatments won't appear when clicking the _Treatments_ button after navigating to the next list of _Phenotypes_ (e.g. beyond 1-10), even if a treatment has been annotated as you can see it does not appear in the 3rd screen capture even though it lists 1 of 1 treatments (so I navigated from the 1st screen capture -> 3rd screen cap).

- obviously dependent on how many phenotypes for the disease and how many you choose to list per page

What should appear is **Calcium Channel Blocking Agent Therapy TREATS Muscle Weakness** (last screen cap)

This behaviour also occurs when navigating from an individual phenotype to 'treatment' if the phenotype is listed in the 2nd page of phenotypes or beyond (so navigating from the 2nd screen cap to treatment -> 3rd screen cap)

Can confirm bug occurs on other disease with more than 10 phenotypes and have treatment annotations (e.g. Marfan syndrome).

![image](https://user-images.githubusercontent.com/86904969/193190853-643edd64-e6fc-4d7d-a827-3b19e223d6f8.png)

![image](https://user-images.githubusercontent.com/86904969/193191175-e054988c-f656-44e7-8931-edfa4ad755ed.png)

![image](https://user-images.githubusercontent.com/86904969/193190866-c7298adb-4838-4cad-b331-ae737d250b2e.png)

![image](https://user-images.githubusercontent.com/86904969/193190925-ef20ab21-6b65-4b72-aff2-6fa41560d402.png)
This will lead to another bug when navigating back to the phenotype list after the treatment doesn't appear, as the phenotype list will be an incorrect 'place' in terms navigation. E.g. this is saying phenotypes 1-10, but it is phenotypes 11-14
(so I navigated from the 3rd screen cap -> 4th screen cap)

![image](https://user-images.githubusercontent.com/86904969/193508292-0f1b8812-2769-4938-9592-fdf317c0a679.png)

**Comment by iimpulse** [comment]
thanks @peupeubangbang closed in #124
