### ISSUE TITLE
New relation: Therapy attempt

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/POET#106]
I think it is also useful to annotate cases where a treatment was tried but did not work.

In the following paper, they tried coenzyme Q10 supplementation (MAXO:0010012) one one patient with no observed benefit

https://pubmed.ncbi.nlm.nih.gov/17186472/

We should use the relation ATTEMPTED_TREATMENT for this?
thoughts @mellybelly @cmungall @LCCarmody ?

**Comment by pnrobinson** [comment]
New relations for POET
1. contraindicated
2. no_observed_benefit

**Comment by iimpulse** [comment]
Acceptance Criteria:

New releations exist and can create with them.

**Comment by iimpulse** [comment]
#124
