### ISSUE TITLE
enforce form of ORCID ids

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/POET#110]
One of the entries in biocuration has the form
```
ORCID:30
```
but valid ORCID ids have the form
```
https://orcid.org/0000-0002-0736-9199
```
or 
```
ORCID:0000-0002-0736-9199
```

**Comment by iimpulse** [comment]
hi @pnrobinson,  where exactly is this? I see I have enforced ORCID validation on the site and have looked in the database and see no such entry?

**Comment by iimpulse** [comment]
Discussed. Keep on data. Enforce ORCID usage.

**Comment by iimpulse** [comment]
Acceptance Criteria:

if your account does not have and orcid attached permanently display a message in the bottom left to add one.

**Comment by BethSundberg** [comment]
Every time I log on it asks for the ID. HOWEVER, if I open the dialog, but don't add a valid Orcid ID, the warning goes away for that session.
