### ISSUE TITLE
Error message for duplicate sources

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/POET#128]
If you try to add a source that is already present, you get this warning
```
[ERROR]: query did not return a unique result: 2; nested exception is javax.persistence.NonUniqueResultException: query did not return a unique result: 2
```
It would be better to provide a plain-language warning.

Also, we should not allow non PubMed sources like this:
https://www.ncbi.nlm.nih.gov/books/NBK525998/
and it would be good to be able to remove or edit sources!

**Comment by iimpulse** [comment]
#131
