### ISSUE TITLE
Could not find a valid disease with id PMID:20301519 or publication with id OMIM:175100.

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/POET#129]
The database entry for Adenomatous Polyposis Coli  (OMIM:175100/MONDO:0021056) seems to be corrupted -- 
there are two source entries for PMID:20301519, but when I try to use them for annotation I get this

```
Could not find a valid disease with id PMID:20301519 or publication with id OMIM:175100.
```

I think I may have added PMID:20301519 a second time, and this is leading to the error? Probably we need to block addition of duplicate entries

**Comment by iimpulse** [comment]
#131
