### ISSUE TITLE
MAxO logo is not displayed properly

### ISSUE THREAD

**Issue by ielis** [TheJacksonLaboratory/POET#62]
Hi team,
I'd like to let you know about a petty issue with `poet.jax.org`. The MAxO logo is not rendering properly (see the screenshot)

![poet_maxo_logo](https://user-images.githubusercontent.com/12170955/145472519-3f630448-89e2-43d4-abe3-4ad69589efd2.png)

Cheers, Daniel

**Comment by iimpulse** [comment]
was this on a particular browser?

**Comment by ielis** [comment]
My `Mozilla Firefox 97.0.2`. Is there any other info that can be helpful?

**Comment by iimpulse** [comment]
Mondo will be fixed soon.
