### ISSUE TITLE
Cannot edit publication for new MAXO annotation

### ISSUE THREAD

**Issue by LCCarmody** [TheJacksonLaboratory/POET#66]
Hi, Partly just writing this ticket b/c I found the link at the bottom of the page and it led me here.

Issue: after submitting an annotation, you can click the pencil icon to edit the annotation, it appears that you can change all of the other items in the annotation EXCEPT the publication. Which is a shame, because the first 2 annotations I made, I would like to change the publication associated with them.

**Comment by iimpulse** [comment]
#72

**Comment by iimpulse** [comment]
#79
