### ISSUE TITLE
Cannot add new HPO terms to maxo annotation

### ISSUE THREAD

**Issue by LCCarmody** [TheJacksonLaboratory/POET#67]
For some reason, it will not let me add new HPO terms. It does seem to remember previous terms that I added, but if I want to use a new one, it doesn't look up any term. When I try to save it, it gives me an error that 'cannot be null', although it doesn't specify what is null. I assume it is the hpo term is not properly looked up and therefore is considered null.

**Comment by iimpulse** [comment]
#79
