### ISSUE TITLE
Viewing phenotypes

### ISSUE THREAD

**Issue by LCCarmody** [TheJacksonLaboratory/POET#70]
I will try to give other specific example. I most often see this with the maxo annotations, but this one should be easy to repeat.

I was searching for a disease using OMIM number (608456) and used the search box while on another disease annotation (I think Bardet-biedl 16).
The disease came up and said 3 phenotypes. No phenotypes appeared. Clicked on Maxo annotations and back to phenotypes and nothing appeared. Then I clicked the 'search by' button and the phenotypes appeared.  

When I went back to the main search page, this didn't happen a second time.  I think it happens if I've been idle or if I've done numerous annotations.

**Comment by iimpulse** [comment]
Could not re-recreate but attempted a fix and added a refresh button in #72

**Comment by iimpulse** [comment]
#79 hopefully fixed :)
