### ISSUE TITLE
Issue using ontology extension

### ISSUE THREAD

**Issue by LCCarmody** [TheJacksonLaboratory/POET#71]
Annotating a term, I am using the MAXO treatment (nonsteroidal anti-inflammatory agent therapy MAXO:0000221) and want to add an additional ontology extension of Sunlindac (CHEBI:9352), but it says "Not valid CHEBI".

Tried both the ID and label of 2 different terms.

**Comment by LCCarmody** [comment]
oh, looks like this is ticket #65

**Comment by iimpulse** [comment]
#95
